/*
 Navicat Premium Data Transfer

 Source Server         : mysql
 Source Server Type    : MySQL
 Source Server Version : 80018
 Source Host           : localhost:3306
 Source Schema         : huisuan

 Target Server Type    : MySQL
 Target Server Version : 80018
 File Encoding         : 65001

 Date: 02/04/2020 14:45:07
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for main_copy
-- ----------------------------
DROP TABLE IF EXISTS `main_copy`;
CREATE TABLE `main_copy`  (
  `clinical_type` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `simple_explain` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `update_columns` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of main_copy
-- ----------------------------
INSERT INTO `main_copy` VALUES ('EVI_000001', '一项临床2期的研究初步表明MET基因扩增的肾癌患者可能对foretinib敏感。', '');
INSERT INTO `main_copy` VALUES ('EVI_000002', '卡博替尼对甲状腺髓样瘤有效，且安全性在可接受范围，同时卡博替尼作为MET, VEGFR2, RET等在甲状腺髓样瘤发病中起重要作用的信号通路基因抑制剂，在临床实验中能带来不错的收效。', '');
INSERT INTO `main_copy` VALUES ('EVI_000004', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000006', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000008', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000009', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000018', 'NCCN推荐携带BRAF V600E的肺癌患者使用维莫非尼治疗；国内外权威指南中，均列明维莫非尼作为BRAFV600突变阳性的不可切除或转移性黑色素瘤一线标准治疗方案。', '');
INSERT INTO `main_copy` VALUES ('EVI_000019', 'NCCN认为具有BRAF V600E突变的结肠癌患者不能从西妥昔单抗、帕尼单抗治疗中获益。', '');
INSERT INTO `main_copy` VALUES ('EVI_000020', 'NCCN认为具有BRAF V600E突变的结肠癌患者不能从西妥昔单抗、帕尼单抗治疗中获益。', '');
INSERT INTO `main_copy` VALUES ('EVI_000021', '肺癌中，EGFR 20 Exon插入突变的发生频率仅次于19 Exon del和21 Exon L858R突变，检测到EGFR A763_Y764insFQEA的患者可以考虑使用TKI治疗，其余的EGFR 20号外显子插入位点不适合TKI治疗(NCCN 指南:NSCLC)。', '');
INSERT INTO `main_copy` VALUES ('EVI_000022', '肺癌中，EGFR 20 Exon插入突变的发生频率仅次于19 Exon del和21 Exon L858R突变，检测到EGFR A763_Y764insFQEA的患者可以考虑使用TKI治疗，其余的EGFR 20号外显子插入位点不适合TKI治疗(NCCN 指南:NSCLC)。', '');
INSERT INTO `main_copy` VALUES ('EVI_000023', '肺癌中，EGFR 20 Exon插入突变的发生频率仅次于19 Exon del和21 Exon L858R突变，检测到EGFR A763_Y764insFQEA的患者可以考虑使用TKI治疗，其余的EGFR 20号外显子插入位点不适合TKI治疗(NCCN 指南:NSCLC)。', '');
INSERT INTO `main_copy` VALUES ('EVI_000024', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000025', '一项研究发现，非小细胞肺癌患者在使用埃克替尼进行治疗耐药后进行NGS检测，部分患者存在EGFR T790M突变。', '');
INSERT INTO `main_copy` VALUES ('EVI_000026', 'NCCN指南报道，EGFR基因的二次突变（如T790M）、MET基因扩增、组织学变化（非小细胞肺癌变成小细胞肺癌）或者上皮细胞一间充质细胞转换可能是肺癌患者对EGFR TKI治疗获得性耐药可能原因。', '');
INSERT INTO `main_copy` VALUES ('EVI_000027', 'NCCN指南报道，EGFR基因的二次突变（如T790M）、MET基因扩增、组织学变化（非小细胞肺癌变成小细胞肺癌）或者上皮细胞一间充质细胞转换可能是肺癌患者对EGFR TKI治疗获得性耐药可能原因。', '');
INSERT INTO `main_copy` VALUES ('EVI_000028', 'NCCN指南报道，EGFR基因的二次突变（如T790M）、MET基因扩增、组织学变化（非小细胞肺癌变成小细胞肺癌）或者上皮细胞一间充质细胞转换可能是肺癌患者对EGFR TKI治疗获得性耐药可能原因。', '');
INSERT INTO `main_copy` VALUES ('EVI_000035', '非小细胞肺癌NCCN指南推荐EGFR 19号外显子缺失、p.L858R、p.L861Q、p.G719X、p.S768I这些突变与酪氨酸激酶抑制剂的敏感性有显著关联，携带这些突变之一的患者对酪氨酸激酶抑制剂（如厄洛替尼、吉非替尼、阿法替尼、奥希替尼、达可替尼）敏感。', '');
INSERT INTO `main_copy` VALUES ('EVI_000041', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000042', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000046', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000047', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000048', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000049', 'NCCN以2A类证据推荐使用靶向药物：携带ROS1融合基因、MET基因高度扩增、MET exon 14 skipping mutation的病人可以使用克唑替尼。', '');
INSERT INTO `main_copy` VALUES ('EVI_000050', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000057', '临床前研究表明，PIK3CA的激活突变（包括基因扩增）可能导致乳腺癌肿瘤细胞株对拉帕替尼耐药。', '');
INSERT INTO `main_copy` VALUES ('EVI_000058', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000059', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000060', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000062', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000063', '一项研究分析了7例奥西替尼(AZD9291)或rociletinib(CO-1686)治疗前后的患者的组织活检样本，发现MET或ERBB2在肿瘤中的复发性扩增导致第三代酪氨酸激酶抑制耐药或耐药进展。', '');
INSERT INTO `main_copy` VALUES ('EVI_000066', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000068', '一项II期临床试验中，使用Ganetespib作为单一疗法来治疗8名携带ALK融合的NSCLC患者，结果显示其中4名患者获得部分缓解。', '');
INSERT INTO `main_copy` VALUES ('EVI_000070', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000071', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000072', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000073', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000075', 'FDA批准达拉非尼、encorafenib + binimetinib、纳武利尤单抗、曲美替尼、cobimetinib用于治疗BRAF V600E突变型黑色素瘤。', '');
INSERT INTO `main_copy` VALUES ('EVI_000076', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000079', 'FDA批准达拉非尼、encorafenib + binimetinib、纳武利尤单抗、曲美替尼、cobimetinib用于治疗BRAF V600E突变型黑色素瘤。', '');
INSERT INTO `main_copy` VALUES ('EVI_000080', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000081', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000082', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000083', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000084', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000085', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000086', 'FDA批准奥拉帕利作为单药治疗之前至少经过3次化疗的晚期卵巢癌患者或BRCA有害突变或疑似有害突变的晚期卵巢癌；欧盟药监局（EMA）也批准了奥拉帕利用于铂敏感复发性卵巢癌患者。', '');
INSERT INTO `main_copy` VALUES ('EVI_000087', 'FDA批准以上药物适用于EGFR 19号外显子缺失或21号外显子 L858R突变的转移性非小细胞肺癌的一线治疗方案。', '');
INSERT INTO `main_copy` VALUES ('EVI_000088', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000089', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000090', 'FDA批准厄洛替尼联合吉西他滨适用于局部晚期、不可切除的或转移性胰腺癌的一线治疗方案。', '');
INSERT INTO `main_copy` VALUES ('EVI_000091', '是FDA批准适用于EGFR 19号外显子缺失或21号外显子 L858R突变的转移性非小细胞肺癌的一线治疗方案。', '');
INSERT INTO `main_copy` VALUES ('EVI_000092', 'FDA批准厄洛替尼联合吉西他滨适用于局部晚期、不可切除的或转移性胰腺癌的一线治疗方案。', '');
INSERT INTO `main_copy` VALUES ('EVI_000093', '是FDA批准适用于EGFR 19号外显子缺失或21号外显子 L858R突变的转移性非小细胞肺癌的一线治疗方案。', '');
INSERT INTO `main_copy` VALUES ('EVI_000094', '是FDA批准适用于EGFR 19号外显子缺失或21号外显子 L858R突变的转移性非小细胞肺癌的一线治疗方案。', '');
INSERT INTO `main_copy` VALUES ('EVI_000099', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000100', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000105', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000106', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000107', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000108', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000109', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000110', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000111', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000112', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000113', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000114', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000115', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000116', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000121', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000122', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000123', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000124', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000125', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000126', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000127', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000128', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000129', '一项临床研究结果显示dabrafenib可能对携带BRAF基因V600E的胃肠道间质瘤患者有一定疗效。', '');
INSERT INTO `main_copy` VALUES ('EVI_000132', '一项临床试验表明，司美替尼联合多西紫杉醇可以延长KRAS突变的非小细胞肺癌患者无进展生存期。', '');
INSERT INTO `main_copy` VALUES ('EVI_000133', '临床研究结果显示，一名携带NRAS Q61K突变的黑色素瘤患者使用MEK/RAF抑制剂（RO5126766）取得了部分缓解。', '');
INSERT INTO `main_copy` VALUES ('EVI_000134', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000140', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000141', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000142', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000143', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000146', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000147', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000148', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000149', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000156', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000157', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000161', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000162', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000163', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000164', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000165', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000166', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000167', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000168', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000169', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000170', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000171', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000172', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000174', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000182', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000183', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000184', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000186', '临床研究表明，refametinib与索拉非尼联用在大部分肝癌患者中都显示出一定的抗肿瘤活性，而且对KRAS基因有突变的患者也有一定疗效。', '');
INSERT INTO `main_copy` VALUES ('EVI_000187', '临床研究表明，携带KRAS基因突变的卵巢癌患者可能对buparlisib（PI3K抑制剂）与曲美替尼（MEK抑制剂）联合治疗有响应。', '');
INSERT INTO `main_copy` VALUES ('EVI_000188', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000190', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000192', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000193', '临床研究表明，refametinib与索拉非尼联用在大部分肝癌患者中都显示出一定的抗肿瘤活性，而且对KRAS基因有突变的患者也有一定疗效。', '');
INSERT INTO `main_copy` VALUES ('EVI_000194', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000195', '我们评估了110例携带KRAS和PIK3CA突变的患者，其中15例携带PIK3CA突变与帕尼单抗或西妥昔单抗的临床耐药显著相关，且没有一个突变患者达到客观反应(P=0.038)。', '');
INSERT INTO `main_copy` VALUES ('EVI_000196', '我们评估了110例携带KRAS和PIK3CA突变的患者，其中15例携带PIK3CA突变与帕尼单抗或西妥昔单抗的临床耐药显著相关，且没有一个突变患者达到客观反应(P=0.038)。', '');
INSERT INTO `main_copy` VALUES ('EVI_000198', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000199', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000200', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000201', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000202', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000203', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000204', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000205', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000206', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000208', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000210', 'STK11与KRAS基因双突变的非小细胞肺癌肿瘤细胞可能对MEK抑制剂CI-1040敏感，对mTOR抑制剂西罗莫司也敏感。', '');
INSERT INTO `main_copy` VALUES ('EVI_000211', '携带TSC1或TSC2突变的膀胱癌患者可能对依维莫司(Everolimus)敏感。', '');
INSERT INTO `main_copy` VALUES ('EVI_000212', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000213', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000214', '一项临床试验表明，MEK抑制剂RO4987655虽然在黑色素瘤和KRAS基因突变的非小细胞肺癌中有效，但对KRAS基因突变的结直肠癌患者无效。', '');
INSERT INTO `main_copy` VALUES ('EVI_000215', '一项临床试验表明，MEK抑制剂RO4987655虽然在黑色素瘤和KRAS基因突变的非小细胞肺癌中有效，但对KRAS基因突变的结直肠癌患者无效。', '');
INSERT INTO `main_copy` VALUES ('EVI_000216', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000221', '一项57例携带KRAS突变肺癌临床试验表明，索拉非尼对携带KRAS突变的NSCLC患者具有相关的临床活性。', '');
INSERT INTO `main_copy` VALUES ('EVI_000227', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000228', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000229', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000230', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000231', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000232', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000233', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000234', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000235', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000236', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000237', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000238', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000239', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000240', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000241', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000242', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000243', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000244', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000245', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000246', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000247', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000248', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000251', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000252', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000254', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000255', '临床试验表明Rociletinib可能对携带EGFR T790M耐药突变非小细胞肿瘤患者敏感。', '');
INSERT INTO `main_copy` VALUES ('EVI_000256', '临床研究表明，refametinib与索拉非尼联用在大部分肝癌患者中都显示出一定的抗肿瘤活性，而且对KRAS基因有突变的患者也有一定疗效。', '');
INSERT INTO `main_copy` VALUES ('EVI_000257', '临床研究表明，refametinib与索拉非尼联用在大部分肝癌患者中都显示出一定的抗肿瘤活性，而且对KRAS基因有突变的患者也有一定疗效。', '');
INSERT INTO `main_copy` VALUES ('EVI_000258', '司美替尼（MEK抑制剂）可能对携带BRAF基因突变的黑色素瘤患者有效，并且能降低肿瘤细胞内AKT的磷酸化水平。', '');
INSERT INTO `main_copy` VALUES ('EVI_000259', 'FDA批准奥拉帕利作为单药治疗之前至少经过3次化疗的晚期卵巢癌患者或BRCA有害突变或疑似有害突变的晚期卵巢癌；欧盟药监局（EMA）也批准了奥拉帕利用于铂敏感复发性卵巢癌患者。', '');
INSERT INTO `main_copy` VALUES ('EVI_000260', 'FDA批准以上药物适用于EGFR 19号外显子缺失或21号外显子 L858R突变的转移性非小细胞肺癌的一线治疗方案。', '');
INSERT INTO `main_copy` VALUES ('EVI_000261', 'FDA批准以上药物适用于EGFR 19号外显子缺失或21号外显子 L858R突变的转移性非小细胞肺癌的一线治疗方案。', '');
INSERT INTO `main_copy` VALUES ('EVI_000263', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000264', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000265', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000268', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000269', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000277', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000278', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000282', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000285', '有临床研究显示针对NSCLC患者如果采用测序方法检测到EGFR 20外显子插入(A763_Y764insFQEA)的患者可以考虑使用TKI治疗，其他的20外显子插入突变位点则不适合TKI治疗。', '');
INSERT INTO `main_copy` VALUES ('EVI_000286', '有临床研究显示针对NSCLC患者如果采用测序方法检测到EGFR 20外显子插入(A763_Y764insFQEA)的患者可以考虑使用TKI治疗，其他的20外显子插入突变位点则不适合TKI治疗。', '');
INSERT INTO `main_copy` VALUES ('EVI_000287', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000289', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000290', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000291', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000292', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000297', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000298', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000299', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000300', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000301', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000302', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000303', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000304', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000305', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000306', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000307', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000308', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000309', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000310', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000315', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000316', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000317', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000318', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000320', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000327', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000328', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000329', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000330', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000331', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000332', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000333', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000334', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000335', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000336', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000337', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000338', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000339', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000340', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000341', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000342', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000343', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000344', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000345', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000346', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000347', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000348', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000349', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000350', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000351', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000361', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000362', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000363', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000364', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000365', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000366', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000367', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000368', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000369', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000371', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000372', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000373', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000374', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000375', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000376', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000377', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000378', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000379', '动物试验表明，帕纳替尼可以对荷瘤小鼠有较好的肿瘤抑制作用。相关临床试验正在进行中。', '');
INSERT INTO `main_copy` VALUES ('EVI_000380', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000381', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000382', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000383', 'FGFR1基因的扩增或者过表达与luminal型乳腺癌预后不良有关，可能导致肿瘤非依赖性生长和对内分泌治疗的耐药。', '');
INSERT INTO `main_copy` VALUES ('EVI_000384', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000387', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000389', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000391', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000392', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000393', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000394', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000395', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000396', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000397', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000398', 'VHL基因失活突变对于抗血管形成治疗有一定的预测价值。回顾性分析发现，携带VHL基因失活突变(无义突变；移码突变等)的肾癌患者可能对VEGFR类抑制剂敏感。', '');
INSERT INTO `main_copy` VALUES ('EVI_000399', 'VHL基因失活突变对于抗血管形成治疗有一定的预测价值。回顾性分析发现，携带VHL基因失活突变(无义突变；移码突变等)的肾癌患者可能对VEGFR类抑制剂敏感。', '');
INSERT INTO `main_copy` VALUES ('EVI_000400', 'VHL基因失活突变对于抗血管形成治疗有一定的预测价值。回顾性分析发现，携带VHL基因失活突变(无义突变；移码突变等)的肾癌患者可能对VEGFR类抑制剂敏感。', '');
INSERT INTO `main_copy` VALUES ('EVI_000401', 'VHL基因失活突变对于抗血管形成治疗有一定的预测价值。回顾性分析发现，携带VHL基因失活突变(无义突变；移码突变等)的肾癌患者可能对VEGFR类抑制剂敏感。', '');
INSERT INTO `main_copy` VALUES ('EVI_000402', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000403', '在一项I期临床试验中，一名携带FBXW7基因失活突变的肝癌患者使用西罗莫司后病情稳定时间延长。', '');
INSERT INTO `main_copy` VALUES ('EVI_000404', '一项临床前研究发现，贝利司他可抑制携带FBXW7基因失活突变的人类血液癌细胞及肿瘤细胞。', '');
INSERT INTO `main_copy` VALUES ('EVI_000405', '一项临床前研究发现，恩替司他可抑制携带FBXW7基因失活突变的晚期实体瘤细胞和血液癌细胞。', '');
INSERT INTO `main_copy` VALUES ('EVI_000406', '一项临床前研究发现，恩替司他可抑制携带FBXW7基因失活突变的晚期实体瘤细胞和血液癌细胞。', '');
INSERT INTO `main_copy` VALUES ('EVI_000407', '一项临床前研究发现，AR-42可抑制携带FBXW7基因失活突变的人类肿瘤细胞及血液癌细胞。', '');
INSERT INTO `main_copy` VALUES ('EVI_000408', '一项临床前研究发现，AR-42可抑制携带FBXW7基因失活突变的人类肿瘤细胞及血液癌细胞。', '');
INSERT INTO `main_copy` VALUES ('EVI_000409', '一项临床前研究发现，贝利司他可抑制携带FBXW7基因失活突变的人类血液癌细胞及肿瘤细胞。', '');
INSERT INTO `main_copy` VALUES ('EVI_000411', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000412', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000413', '一项临床前研究发现，细胞培养和异体移植模型中，携带FBXW7基因突变的乳腺癌细胞系表现出对西罗莫司的敏感性。', '');
INSERT INTO `main_copy` VALUES ('EVI_000414', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000415', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000416', 'I期临床试验分析表明，携带FGFR1基因扩增的肿瘤患者在使用多韦替尼治疗后疾病稳定。', '');
INSERT INTO `main_copy` VALUES ('EVI_000417', '临床前研究表明，司美替尼无法抑制携带FGFR2基因扩增的胃癌细胞增殖。', '');
INSERT INTO `main_copy` VALUES ('EVI_000418', '临床前研究表明，携带FGFR2基因激活突变的肿瘤患者可能对帕纳替尼敏感。', '');
INSERT INTO `main_copy` VALUES ('EVI_000419', '临床前研究表明，携带FGFR2基因激活突变的肿瘤患者可能对多韦替尼敏感。', '');
INSERT INTO `main_copy` VALUES ('EVI_000420', 'I期临床试验表明，携带FGFR2基因扩增的乳腺癌患者可能对多韦替尼敏感。', '');
INSERT INTO `main_copy` VALUES ('EVI_000421', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000422', 'I期临床试验表明，JNJ-42756493(erdafitinib)可能对携带FGFR1-4基因发生激活突变的肿瘤患者有效。', '');
INSERT INTO `main_copy` VALUES ('EVI_000423', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000424', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000425', 'I期临床试验表明，CH5183284(debio1347)可能对携带FGFR基因发生激活突变的肿瘤患者有效。', '');
INSERT INTO `main_copy` VALUES ('EVI_000427', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000428', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000429', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000432', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000433', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000434', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000435', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000436', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000437', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000438', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000439', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000440', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000441', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000442', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000446', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000447', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000448', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000449', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000450', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000451', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000452', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000455', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000458', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000460', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000461', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000462', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000463', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000464', '中国埃克替尼治疗非小细胞肺癌专家共识（2016年版）推荐埃克替尼适用于单药适用于治疗既往接受过至少一个化疗方案失败后的局部晚期或转移性非小细胞肺癌（NSCLC），且EGFR突变型患者疗效优于野生型患者。', '');
INSERT INTO `main_copy` VALUES ('EVI_000465', '是FDA批准适用于EGFR 19号外显子缺失或21号外显子 L858R突变的转移性非小细胞肺癌的一线治疗方案。', '');
INSERT INTO `main_copy` VALUES ('EVI_000468', 'FDA批准以上药物适用于EGFR 19号外显子缺失或21号外显子 L858R突变的转移性非小细胞肺癌的一线治疗方案。', '');
INSERT INTO `main_copy` VALUES ('EVI_000469', '中国埃克替尼治疗非小细胞肺癌专家共识（2016年版）推荐埃克替尼适用于单药适用于治疗既往接受过至少一个化疗方案失败后的局部晚期或转移性非小细胞肺癌（NSCLC），且EGFR突变型患者疗效优于野生型患者。', '');
INSERT INTO `main_copy` VALUES ('EVI_000470', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000473', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000474', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000475', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000476', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000477', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000478', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000479', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000480', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000481', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000482', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000483', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000484', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000485', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000486', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000487', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000488', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000489', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000490', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000491', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000499', '细胞学试验表明，阿法替尼可下调EGFR和ERBB2信号通路，产生抗肿瘤作用。', '');
INSERT INTO `main_copy` VALUES ('EVI_000500', '在临床前研究中，Niclosamide可以抑制携带APC突变的结肠直肠癌细胞的增殖。', '');
INSERT INTO `main_copy` VALUES ('EVI_000501', '在临床前研究中，vandetanib抑制了APC缺陷小鼠模型中的葡聚糖硫酸钠诱导的肿瘤的生长。', '');
INSERT INTO `main_copy` VALUES ('EVI_000502', '在临床前研究中，塞来昔布与厄洛替尼组合，在APC失活突变小鼠和结肠直肠癌的异种移植模型中显著减少肿瘤大小。', '');
INSERT INTO `main_copy` VALUES ('EVI_000503', '在临床前研究中，达沙替尼和姜黄素的组合可以抑制携带APC突变的结肠直肠癌小鼠模型中肿瘤的生长。', '');
INSERT INTO `main_copy` VALUES ('EVI_000507', '在临床前试验中，显示西罗莫司在家族性腺瘤性息肉病和具有APC缺陷型肿瘤的结肠癌的小鼠模型中可有效减少肿瘤大小。', '');
INSERT INTO `main_copy` VALUES ('EVI_000508', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000509', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000510', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000514', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000516', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000517', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000518', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000519', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000521', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000522', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000523', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000524', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000525', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000526', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000527', '在临床前研究中，携带NRAS Q61K基因突变的肿瘤细胞对培养物中的奥希替尼具有抗性。', '');
INSERT INTO `main_copy` VALUES ('EVI_000528', '在临床前研究中，携带NRAS基因Q61K突变的人非小细胞肺癌细胞对培养物中的Gedatolisib的反应较低。', '');
INSERT INTO `main_copy` VALUES ('EVI_000529', '在临床前研究中，Pimasertib抑制携带NRAS Q61K的非小细胞肺癌细胞的增殖。', '');
INSERT INTO `main_copy` VALUES ('EVI_000530', '在临床前研究中，携带NRAS Q61K突变的黑色素瘤细胞对维莫非尼具有抗性。', '');
INSERT INTO `main_copy` VALUES ('EVI_000531', '在临床前研究中，司美替尼适度抑制携带NRAS Q61L基因突变的人黑色素瘤细胞的增殖', '');
INSERT INTO `main_copy` VALUES ('EVI_000532', '在临床前研究中，BI-847325可以抑制具有NRAS突变的黑色素瘤细胞系的生长。', '');
INSERT INTO `main_copy` VALUES ('EVI_000533', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000534', '在临床前研究中，携带NRAS Q61K突变的黑色素瘤细胞对维莫非尼具有抗性。', '');
INSERT INTO `main_copy` VALUES ('EVI_000535', '在临床前研究中，携带NRAS Q61K基因突变的肿瘤细胞对培养物中的奥希替尼具有抗性。', '');
INSERT INTO `main_copy` VALUES ('EVI_000536', '在临床前研究中，携带NRAS Q61K基因突变的肿瘤细胞对培养物中的奥希替尼具有抗性。', '');
INSERT INTO `main_copy` VALUES ('EVI_000539', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000545', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000546', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000547', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000548', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000549', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000550', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000551', '体外实验表明KRAS和BRAF的突变则导致细胞对依维莫司的耐药性。', '');
INSERT INTO `main_copy` VALUES ('EVI_000552', '一项临床Ⅱ期试验中，对结直肠癌患者使用mTOR抑制剂依维莫司治疗，根据依维莫司给药剂量分为70 mg/周和10 mg/天两组，70 mg/周治疗时患者无进展生存期、总存活率及疾病控制率无显著差异，10 mg/天治疗时，具有KRAS/BRAF突变患者预后较差。', '');
INSERT INTO `main_copy` VALUES ('EVI_000553', '一项临床II期试验的结果显示结直肠癌患者无法从依维莫司的单一治疗中获益。', '');
INSERT INTO `main_copy` VALUES ('EVI_000554', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000557', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000558', 'XL647（tesevatinib）是一种有效的EGFR、VEGFR2、HER2和EphB4抑制剂。一项临床试验表明，携带T790M突变的肺癌患者接受XL647治疗相比无突变的患者预后效果更差。', '');
INSERT INTO `main_copy` VALUES ('EVI_000563', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000564', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000569', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000570', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000572', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000573', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000574', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000575', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000578', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000579', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000580', 'FDA批准rucaparib治疗BRCA有害突变（生殖细胞和/或体细胞）相关的晚期卵巢癌。', '');
INSERT INTO `main_copy` VALUES ('EVI_000581', 'FDA批准rucaparib治疗BRCA有害突变（生殖细胞和/或体细胞）相关的晚期卵巢癌。', '');
INSERT INTO `main_copy` VALUES ('EVI_000582', '一项临床试验表明，在结直肠癌患者中EGFR基因扩增可能对西妥昔单抗/帕尼单抗敏感。', '');
INSERT INTO `main_copy` VALUES ('EVI_000583', '一项临床试验表明，在结直肠癌患者中EGFR基因扩增可能对西妥昔单抗/帕尼单抗敏感。', '');
INSERT INTO `main_copy` VALUES ('EVI_000584', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000585', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000586', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000587', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000588', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000589', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000590', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000591', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000592', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000593', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000594', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000595', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000596', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000597', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000598', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000599', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000600', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000601', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000602', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000603', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000604', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000605', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000606', '一项研究发现EGFR介导的MAPK通路重新激活可能与维莫非尼在BRAF突变结直肠癌患者中的耐药相关，维莫非尼治疗结直肠癌患者的临床反应率低于5%。', '');
INSERT INTO `main_copy` VALUES ('EVI_000607', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000608', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000609', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000612', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000613', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000614', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000615', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000617', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000618', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000619', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000620', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000621', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000622', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000623', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000624', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000625', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000626', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000629', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000630', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000631', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000632', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000633', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000634', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000635', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000636', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000637', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000638', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000639', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000640', '一项临床Ⅱ期试验中，对结直肠癌患者使用mTOR抑制剂依维莫司治疗，根据依维莫司给药剂量分为70 mg/周和10 mg/天两组，70 mg/周治疗时患者无进展生存期、总存活率及疾病控制率无显著差异，10 mg/天治疗时，具有KRAS/BRAF突变患者预后较差。', '');
INSERT INTO `main_copy` VALUES ('EVI_000641', '一项关于依维莫司的临床II期试验表明KRAS突变的子宫内膜癌患者对依维莫司可能耐药。', '');
INSERT INTO `main_copy` VALUES ('EVI_000642', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000645', '临床试验结果显示，携带NRAS基因突变的黑色素瘤患者在对仑伐替尼治疗可能敏感。', '');
INSERT INTO `main_copy` VALUES ('EVI_000646', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000647', '在临床前研究中，MK-1775在NRAS突变型黑色素瘤、KRAS突变型结肠直肠癌、胰腺癌和肺癌中显示出肿瘤抑制作用。', '');
INSERT INTO `main_copy` VALUES ('EVI_000648', '在临床前研究中，MK2206可以抑制培养物中携带NRAS基因激活突变（Q61R）的间变甲状腺癌细胞的生长。', '');
INSERT INTO `main_copy` VALUES ('EVI_000649', '在临床前研究中，奥巴克拉（obatoclax）可以抑制NRAS突变的人肿瘤细胞的增殖。', '');
INSERT INTO `main_copy` VALUES ('EVI_000650', '在临床前研究中，哌柏西利不能抑制携带NRAS突变的黑色素瘤细胞的生长。', '');
INSERT INTO `main_copy` VALUES ('EVI_000651', '在临床前研究中，PD-0325901不能抑制具有NRAS突变的黑色素瘤细胞系异种移的肿瘤生长。', '');
INSERT INTO `main_copy` VALUES ('EVI_000652', '在I期研究中，司美替尼在一个亚组的放射性碘难治的甲状腺癌患者中表现出碘吸收和保留增加；此类患者包括携带BRAF和NRAS基因突变。', '');
INSERT INTO `main_copy` VALUES ('EVI_000653', '在临床前研究中，携带NRAS Q61K突变的黑色素瘤细胞对维莫非尼具有抗性。', '');
INSERT INTO `main_copy` VALUES ('EVI_000656', 'NCCN临床指南（NSCLC，2018 V6版）提示KRAS基因突变与肿瘤患者对EGFR抑制剂的原发耐药有关，主要是由于KRAS和NRAS基因exons2（codons 12 and 13），3（codons 59 and 61）以及4（codons 117 and 146）位点的突变会导致RAS信号通路的异常活化，不受上游EGFR信号影响。', '');
INSERT INTO `main_copy` VALUES ('EVI_000657', 'NCCN临床指南（NSCLC，2018 V6版）提示KRAS基因突变与肿瘤患者对EGFR抑制剂的原发耐药有关，主要是由于KRAS和NRAS基因exons2（codons 12 and 13），3（codons 59 and 61）以及4（codons 117 and 146）位点的突变会导致RAS信号通路的异常活化，不受上游EGFR信号影响。', '');
INSERT INTO `main_copy` VALUES ('EVI_000658', 'NCCN指南提示携带KRAS或者NRAS激活突变的肿瘤患者不应当使用EGFR单抗类药物（如西妥昔单抗或帕尼单抗）。', '');
INSERT INTO `main_copy` VALUES ('EVI_000659', 'NCCN临床指南（NSCLC，2018 V6版）提示KRAS基因突变与肿瘤患者对EGFR抑制剂的原发耐药有关，主要是由于KRAS和NRAS基因exons2（codons 12 and 13），3（codons 59 and 61）以及4（codons 117 and 146）位点的突变会导致RAS信号通路的异常活化，不受上游EGFR信号影响。', '');
INSERT INTO `main_copy` VALUES ('EVI_000660', 'NCCN临床指南（NSCLC，2018 V6版）提示KRAS基因突变与肿瘤患者对EGFR抑制剂的原发耐药有关，主要是由于KRAS和NRAS基因exons2（codons 12 and 13），3（codons 59 and 61）以及4（codons 117 and 146）位点的突变会导致RAS信号通路的异常活化，不受上游EGFR信号影响。', '');
INSERT INTO `main_copy` VALUES ('EVI_000661', 'NCCN临床指南（NSCLC，2018 V6版）提示KRAS基因突变与肿瘤患者对EGFR抑制剂的原发耐药有关，主要是由于KRAS和NRAS基因exons2（codons 12 and 13），3（codons 59 and 61）以及4（codons 117 and 146）位点的突变会导致RAS信号通路的异常活化，不受上游EGFR信号影响。', '');
INSERT INTO `main_copy` VALUES ('EVI_000662', 'NCCN临床指南（NSCLC，2018 V6版）提示KRAS基因突变与肿瘤患者对EGFR抑制剂的原发耐药有关，主要是由于KRAS和NRAS基因exons2（codons 12 and 13），3（codons 59 and 61）以及4（codons 117 and 146）位点的突变会导致RAS信号通路的异常活化，不受上游EGFR信号影响。', '');
INSERT INTO `main_copy` VALUES ('EVI_000663', 'KRAS和NRAS基因exons2（codons 12 and 13），3（codons 59 and 61）以及4（codons 117 and 146）位点的突变会导致RAS信号通路的异常活化，不受上游EGFR信号影响，NCCN临床指南提示KRAS基因突变与肿瘤患者对EGFR抑制剂的原发耐药有关。', '');
INSERT INTO `main_copy` VALUES ('EVI_000664', 'NCCN指南提示携带KRAS或者NRAS激活突变的肿瘤患者不应当使用EGFR单抗类药物（如西妥昔单抗或帕尼单抗）。', '');
INSERT INTO `main_copy` VALUES ('EVI_000665', '结直肠癌患者需要检测KRAS、NRAS和BRAF基因的突变状态。携带这些基因激活突变的肿瘤患者不应当使用EGFR抗体药物（如西妥昔单抗或帕尼单抗）。', '');
INSERT INTO `main_copy` VALUES ('EVI_000666', '结直肠癌患者需要检测KRAS、NRAS和BRAF基因的突变状态。携带这些基因激活突变的肿瘤患者不应当使用EGFR抗体药物（如西妥昔单抗或帕尼单抗）。', '');
INSERT INTO `main_copy` VALUES ('EVI_000667', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000672', '有临床研究显示针对NSCLC患者如果采用测序方法检测到EGFR 20外显子插入(A763_Y764insFQEA)的患者可以考虑使用TKI治疗，其他的20外显子插入突变位点则不适合TKI治疗。', '');
INSERT INTO `main_copy` VALUES ('EVI_000673', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000674', 'NCCN指南推荐KRAS、NRAS和BRAF野生型结直肠癌患者可以从EGFR单抗（西妥昔单抗或帕尼单抗）治疗中获益。', '');
INSERT INTO `main_copy` VALUES ('EVI_000675', 'NCCN指南推荐KRAS、NRAS和BRAF野生型结直肠癌患者可以从EGFR单抗（西妥昔单抗或帕尼单抗）治疗中获益。', '');
INSERT INTO `main_copy` VALUES ('EVI_000680', 'NCCN推荐携带BRAF V600E的肺癌患者使用维莫非尼治疗；国内外权威指南中，均列明维莫非尼作为BRAFV600突变阳性的不可切除或转移性黑色素瘤一线标准治疗方案。', '');
INSERT INTO `main_copy` VALUES ('EVI_000681', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000682', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000683', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000684', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000685', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000686', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000687', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000688', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000689', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000690', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000691', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000692', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000693', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000694', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000695', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000696', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000697', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000698', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000699', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000700', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000701', '2017年1月，权威医学杂志《柳叶刀》公布了罗氏的PD-L1抗体阿替利珠单抗对比多西他赛用于晚期非小细胞肺癌的三期临床数据：结果表明， 阿替利珠单抗针对EGFR突变且靶向药物耐药的患者，疗效较多西他赛相比差一些。', '');
INSERT INTO `main_copy` VALUES ('EVI_000704', 'FDA批准达拉非尼、encorafenib + binimetinib、纳武利尤单抗、曲美替尼、cobimetinib用于治疗BRAF V600E突变型黑色素瘤。', '');
INSERT INTO `main_copy` VALUES ('EVI_000710', 'FDA批准了TESARO公司研发的PARP类口服抑制剂Niraparib，作为维持治疗用于治疗对铂类化疗敏感的复发上皮性卵巢癌、输卵管癌及原发性腹膜癌患者。', '');
INSERT INTO `main_copy` VALUES ('EVI_000711', 'FDA批准了TESARO公司研发的PARP类口服抑制剂Niraparib，作为维持治疗用于治疗对铂类化疗敏感的复发上皮性卵巢癌、输卵管癌及原发性腹膜癌患者。', '');
INSERT INTO `main_copy` VALUES ('EVI_000712', 'FDA批准了TESARO公司研发的PARP类口服抑制剂Niraparib，作为维持治疗用于治疗对铂类化疗敏感的复发上皮性卵巢癌、输卵管癌及原发性腹膜癌患者。', '');
INSERT INTO `main_copy` VALUES ('EVI_000713', 'FDA批准了TESARO公司研发的PARP类口服抑制剂Niraparib，作为维持治疗用于治疗对铂类化疗敏感的复发上皮性卵巢癌、输卵管癌及原发性腹膜癌患者。', '');
INSERT INTO `main_copy` VALUES ('EVI_000714', 'FDA批准了TESARO公司研发的PARP类口服抑制剂Niraparib，作为维持治疗用于治疗对铂类化疗敏感的复发上皮性卵巢癌、输卵管癌及原发性腹膜癌患者。', '');
INSERT INTO `main_copy` VALUES ('EVI_000715', 'FDA批准了TESARO公司研发的PARP类口服抑制剂Niraparib，作为维持治疗用于治疗对铂类化疗敏感的复发上皮性卵巢癌、输卵管癌及原发性腹膜癌患者。', '');
INSERT INTO `main_copy` VALUES ('EVI_000716', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000717', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000718', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000719', '一项单臂，多中心，II期临床试验研究MET状态与savolitinib在PRCC患者中的安全性和有效性，结果发现MET驱动突变患者与治疗响应密切相关,8例MET突变患者取得部分响应，而所有MET野生型均无治疗响应。', '');
INSERT INTO `main_copy` VALUES ('EVI_000720', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000723', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000724', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000731', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000732', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000738', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000739', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000740', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000741', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000742', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000743', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000755', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000756', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000758', 'SWOG S1406临床试验表明，携带BRAF V600E突变及RAS突变的转移性结直肠癌患者无法从伊立替康 + 维莫非尼 + 西妥昔单抗的联合治疗方案中获益。', '');
INSERT INTO `main_copy` VALUES ('EVI_000759', 'SWOG S1406临床试验，入组99例携带BRAF突变但RAS野生型的转移性结直肠癌患者，使用伊立替康+西妥昔单抗±维莫非尼联合治疗方案疗效显著改善，而BRAF V600E且同时携带RAS突变患者可能不能从该联合治疗方案中获益。', '');
INSERT INTO `main_copy` VALUES ('EVI_000760', 'CMAB009是西妥昔单抗的生物类似物，有研究入组512例KRAS野生型转移性结直肠癌患者，一线奥沙利铂+氟尿嘧啶治疗失败，后续服用伊立替康联合CMAB009，显著提高ORR。', '');
INSERT INTO `main_copy` VALUES ('EVI_000761', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000762', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000763', '一项II期临床试验，入组HER2扩增的胃食管癌患者，20名接受阿法替尼单药治疗的患者中，5人肿瘤缩小；12名接受阿法替尼联合赫赛汀治疗的患者中，1名患者肿瘤明显缩小，2人肿瘤稳定超过4个月。', '');
INSERT INTO `main_copy` VALUES ('EVI_000764', '临床试验报道，27例接受一线或一线后治疗进展的HER2阳性晚期胃癌患者，应用dacomitinib单药治疗，中位PFS及OS分别为2.1个月及7.1个月，疾病控制率为40.7%（2例PR，9例SD）。', '');
INSERT INTO `main_copy` VALUES ('EVI_000765', '一项临床试验共纳入45例MET扩增（FISH）的患者（25例先前接受过第三代EGFR-TKI治疗，20例未经第三代EGFR-TKI治疗），评估接受osimertinib 80 mg加savolitinib 600 mg的疗效，研究发现先前用第三代EGFR-TKI治疗的患者中20%有响应；未使用EGFR-TKI的患者中，T790M阴性患者中42%有响应，T790M阳性患者43%有响应。', '');
INSERT INTO `main_copy` VALUES ('EVI_000766', 'Ib期临床研究（NCT02374645）评估了沃利替尼联合吉非替尼治疗既往EGFR TKI治疗后进展的中国晚期EGFR突变NSCLC中国患者，结果发现 25%的患者部分缓解，4例患者待确认疗效。12周后进行研究评估，共有46%的患者持续接受治疗。', '');
INSERT INTO `main_copy` VALUES ('EVI_000767', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000768', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000769', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000770', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000771', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000772', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000773', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000774', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000775', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000776', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000777', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000779', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000780', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000781', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000783', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000784', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000785', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000789', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000790', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000791', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000792', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000793', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000794', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000795', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000796', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000797', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000798', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000799', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000800', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000801', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000803', '一项临床II期研究结果显示EGFR基因扩增阳性肺癌患者进行化疗联合西妥昔单抗的治疗，其无进展生存期（PFS）和总生存期（OS）都明显好于EGFR基因扩增阴性患者。', '');
INSERT INTO `main_copy` VALUES ('EVI_000806', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000807', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000809', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000810', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000813', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000815', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000816', 'PI3K作为KIT信号通路的下游基因，在包括GIST的多种癌症类型中都发现也可能发生激活突变。由于二次KIT突变或KIT信号传导途径下游的激活（如PI3K/AKT/mTOR途径），可能导致患者对酪氨酸激酶抑制剂如伊马替尼产生耐药。', '');
INSERT INTO `main_copy` VALUES ('EVI_000817', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000818', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000820', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000821', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000826', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000827', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000828', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000829', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000830', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000831', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000835', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000836', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000837', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000838', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000839', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000840', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000850', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000851', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000852', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000853', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000854', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000855', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000858', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000859', '一名携带BRAF V600E突变的胆管癌患者在采用维莫非尼和帕尼单抗的联合治疗并辅以伊立替康治疗后表现出临床完全反应；一名携带BRAF V600E突变的间变性少突细胞瘤患者口服vemurafenib后病情稳定了6个月。', '');
INSERT INTO `main_copy` VALUES ('EVI_000860', '一位携带BRAF V600E突变的结肠癌患者在接受索拉非尼 + 西妥昔单抗治疗后表现出超乎寻常的良好表现，疾病稳定且不良反应轻微；后续该患者改用帕尼单抗 + 瑞戈非尼的组合来优化治疗并避免可能出现的耐药性，患者一直表现良好，无严重的不良反应。', '');
INSERT INTO `main_copy` VALUES ('EVI_000861', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000863', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000864', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000865', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000866', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000867', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000868', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000869', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000870', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000871', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000873', '2017年4月，在美国癌症研究协会年会（AACR2017）上一项I期临床研究显示，入组的17例携带KRAS突变的肺癌患者，MEK抑制剂（PD-0325901）和哌柏西利的联合使用是安全、可耐受的，而且确定有患者能从这一组合用药中获益。', '');
INSERT INTO `main_copy` VALUES ('EVI_000874', '一项临床研究显示，在KRAS突变的小鼠模型中，同时存在另一种叫做Keap 1的突变基因时，小鼠体内的肿瘤生长得更快。而CB-839能有效遏制Keap 1突变，肿瘤就不能继续生长。', '');
INSERT INTO `main_copy` VALUES ('EVI_000875', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000876', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000877', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000878', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000879', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000880', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000881', '一项临床试验评估103名HER2阳性非小细胞肺癌患者采用吉西他滨+顺铂与吉西他滨+顺铂+曲妥珠单抗临床疗效，显示HER2阳性的非小细胞肺癌患者可能无法从曲妥珠单抗的治疗中获益。', '');
INSERT INTO `main_copy` VALUES ('EVI_000882', '携带ERBB2基因激活突变（例如Exon20插入，S310F/Y，L755S等），的肿瘤细胞可能对ERBB2抑制剂敏感。一项II期临床试验正在评估neratinib在携带ERBB2激活突变的肿瘤患者中的疗效。', '');
INSERT INTO `main_copy` VALUES ('EVI_000883', '携带ERBB2基因激活突变（例如Exon20插入，S310F/Y，L755S等），的肿瘤细胞可能对ERBB2抑制剂敏感。一项II期临床试验正在评估neratinib在携带ERBB2激活突变的肿瘤患者中的疗效。', '');
INSERT INTO `main_copy` VALUES ('EVI_000885', 'AZD3759对于EGFR敏感性突变，主要是L858R和Exon19Del，其与目前批准的EGFR TKIs相比，透过血脑屏障（BBB）的功能更强。一项临床试验显示，从未接受过EGFR TKI治疗且具有脑转移的患者经AZD3759治疗后，83%的患者获得客观响应。', '');
INSERT INTO `main_copy` VALUES ('EVI_000886', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000888', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000890', '一项纳入了404例贝伐珠单抗治疗的转移性结直肠癌患者的研究显示，使用贝伐珠单抗治疗时，携带G12V/A KRAS突变的肿瘤患者与野生型患者相比，前者的PFS和OS都劣于后者（提示：KRAS G12/13两个位点的所有突变，生物学上认为是等效的，临床意义也差不多）。', '');
INSERT INTO `main_copy` VALUES ('EVI_000892', '非小细胞肺癌NCCN指南推荐EGFR 19号外显子缺失、p.L858R、p.L861Q、p.G719X、p.S768I这些突变与酪氨酸激酶抑制剂的敏感性有显著关联，携带这些突变之一的患者对酪氨酸激酶抑制剂（如厄洛替尼、吉非替尼、阿法替尼、奥希替尼、达可替尼）敏感。', '');
INSERT INTO `main_copy` VALUES ('EVI_000893', '非小细胞肺癌NCCN指南推荐EGFR 19号外显子缺失、p.L858R、p.L861Q、p.G719X、p.S768I这些突变与酪氨酸激酶抑制剂的敏感性有显著关联，携带这些突变之一的患者对酪氨酸激酶抑制剂（如厄洛替尼、吉非替尼、阿法替尼、奥希替尼、达可替尼）敏感。', '');
INSERT INTO `main_copy` VALUES ('EVI_000894', '非小细胞肺癌NCCN指南推荐EGFR 19号外显子缺失、p.L858R、p.L861Q、p.G719X、p.S768I这些突变与酪氨酸激酶抑制剂的敏感性有显著关联，携带这些突变之一的患者对酪氨酸激酶抑制剂（如厄洛替尼、吉非替尼、阿法替尼、奥希替尼、达可替尼）敏感。', '');
INSERT INTO `main_copy` VALUES ('EVI_000895', 'I期临床试验表明，pictilisib的安全性和抗肿瘤活性良好；一名PTEN基因缺失+PIK3CA基因拷贝数扩增的卵巢癌患者，在pictilisib治疗后取得了部分响应。', '');
INSERT INTO `main_copy` VALUES ('EVI_000896', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000898', '一名携带PIK3CA激活突变的乳腺癌患者使用依维莫司与阿那曲唑的联合治疗后取得了部分响应。', '');
INSERT INTO `main_copy` VALUES ('EVI_000899', '一名携带PIK3CA激活突变的口咽癌患者使用依维莫司后肿瘤减少了58%。', '');
INSERT INTO `main_copy` VALUES ('EVI_000900', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000901', '一名携带PIK3CA激活突变的卵巢癌病人使用哌立福新联合多西他赛治疗后疾病稳定了4个月。', '');
INSERT INTO `main_copy` VALUES ('EVI_000902', '一例临床对BRAF V600E突变GIST患者使用达拉非尼后出现了抗肿瘤活性延长现象，检测发现患者体细胞出现获得性PIK3CA突变(H1047R)突变，这可能最终导致患者耐药。', '');
INSERT INTO `main_copy` VALUES ('EVI_000903', '一名携带PIK3CA基因激活突变（H1047R）的卵巢癌患者对CH5132799（PI3K抑制剂）治疗有部分响应。', '');
INSERT INTO `main_copy` VALUES ('EVI_000904', '研究显示：表达PIK3CA激活突变的肿瘤细胞株对temsirolimus敏感。', '');
INSERT INTO `main_copy` VALUES ('EVI_000907', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000908', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000909', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000910', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000911', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000912', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000913', 'NCCN指南中指出，肺癌患者对EGFR-TKI出现获得性耐药的原因包括：EGFR基因上的二次突变（如T790M），MET基因的扩增，NSCLC到SCLC的组织转化，以及上皮到间质的转化。', '');
INSERT INTO `main_copy` VALUES ('EVI_000914', 'NCCN指南中指出，肺癌患者对EGFR-TKI出现获得性耐药的原因包括：EGFR基因上的二次突变（如T790M），MET基因的扩增，NSCLC到SCLC的组织转化，以及上皮到间质的转化。', '');
INSERT INTO `main_copy` VALUES ('EVI_000915', 'NCCN指南中指出，肺癌患者对EGFR-TKI出现获得性耐药的原因包括：EGFR基因上的二次突变（如T790M），MET基因的扩增，NSCLC到SCLC的组织转化，以及上皮到间质的转化。', '');
INSERT INTO `main_copy` VALUES ('EVI_000916', 'NCCN指南中指出，肺癌患者对EGFR-TKI出现获得性耐药的原因包括：EGFR基因上的二次突变（如T790M），MET基因的扩增，NSCLC到SCLC的组织转化，以及上皮到间质的转化。', '');
INSERT INTO `main_copy` VALUES ('EVI_000917', 'NCCN指南中指出，肺癌患者对EGFR-TKI出现获得性耐药的原因包括：EGFR基因上的二次突变（如T790M），MET基因的扩增，NSCLC到SCLC的组织转化，以及上皮到间质的转化。', '');
INSERT INTO `main_copy` VALUES ('EVI_000918', '一项关于胰腺癌患者对厄洛替尼的临床试验显示，KRAS状态与厄洛替尼疗效的客观反应无关，但KRAS野生型患者OS有明显改善， KRAS野生型患者在（无厄洛替尼）2线化疗期间也观察到生存期增加的趋势。', '');
INSERT INTO `main_copy` VALUES ('EVI_000919', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000920', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000921', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000924', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000925', '是FDA批准适用于EGFR 19号外显子缺失或21号外显子 L858R突变的转移性非小细胞肺癌的一线治疗方案。', '');
INSERT INTO `main_copy` VALUES ('EVI_000926', 'FDA批准奥希替尼（泰瑞沙）适用于EGFR 19号外显子缺失或21号外显子 L858R突变的转移性非小细胞肺癌的一线治疗方案；FDA还批准了奥希替尼用于EGFR TKI治疗后发生EGFR T790M突变阳性的转移性非小细胞肺癌患者的治疗。', '');
INSERT INTO `main_copy` VALUES ('EVI_000928', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000929', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000930', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000931', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000932', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000933', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000935', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000936', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000937', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000938', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000939', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000940', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000941', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000942', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000943', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000944', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000945', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000946', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000947', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000949', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000950', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000951', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000953', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000954', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000955', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000956', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000957', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000958', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000959', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000960', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000961', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000962', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000963', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000964', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000965', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000966', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000967', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000968', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000969', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000970', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000971', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000972', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000973', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000975', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000977', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000978', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000979', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000980', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000981', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000982', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000983', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000985', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000986', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000987', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000988', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000991', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000993', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000995', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000996', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000997', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000998', '', '');
INSERT INTO `main_copy` VALUES ('EVI_000999', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001000', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001001', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001002', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001003', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001004', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001005', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001006', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001007', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001008', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001009', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001010', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001011', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001012', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001013', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001014', '一项临床试验结果显示，入组的21例肿瘤患者中，有12例对MK-2206治疗有反应，其中1位患者检测到PIK3CA扩增。', '');
INSERT INTO `main_copy` VALUES ('EVI_001015', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001016', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001017', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001018', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001019', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001020', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001021', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001022', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001023', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001026', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001027', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001028', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001029', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001031', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001032', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001034', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001035', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001036', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001037', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001038', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001040', '体外试验表明，携带ERBB2基因激活突变的肿瘤细胞株可能对来那替尼或EXEL-7647（tesevatinib）敏感。', '');
INSERT INTO `main_copy` VALUES ('EVI_001041', '体外试验表明，携带ERBB2基因激活突变的肿瘤细胞株可能对来那替尼或EXEL-7647（tesevatinib）敏感。', '');
INSERT INTO `main_copy` VALUES ('EVI_001044', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001045', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001046', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001047', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001049', 'NCCN指南基于一项3058例入组患者的研究，评估2334例KRAS野生型转移性结直肠癌患者使用FOLFOX+ 西妥昔单抗有效。', '');
INSERT INTO `main_copy` VALUES ('EVI_001050', 'NCCN指南基于CRYSTAL（NCT00154102）研究，评估转移性结直肠癌患者KRAS野生型亚组中，FOLFIRI+西妥昔单抗疗效优于FOLFIRI。', '');
INSERT INTO `main_copy` VALUES ('EVI_001051', 'FDA基于NCT00364013研究，批准KRAS野生型转移性结直肠癌患者使用帕尼单抗+FOLFOX。', '');
INSERT INTO `main_copy` VALUES ('EVI_001052', 'NCCN指南基于一项入组1186例转移性结直肠癌患者试验，推荐KRAS野生型患者可以使用FOLFIRI + 帕尼单抗的治疗方案。', '');
INSERT INTO `main_copy` VALUES ('EVI_001053', 'FDA批准达拉非尼、encorafenib + binimetinib、纳武利尤单抗、曲美替尼、cobimetinib用于治疗BRAF V600E突变型黑色素瘤。', '');
INSERT INTO `main_copy` VALUES ('EVI_001054', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001057', '细胞学试验表明，osimertinib对携带ERBB2激活突变的肿瘤细胞，如L755P和L755S，具有一定的抑制作用。', '');
INSERT INTO `main_copy` VALUES ('EVI_001059', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001061', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001062', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001063', 'Ib/II期研究调查了capmatinib联合吉非替尼治疗EGFR突变、MET失调（扩增/过度表达）的NSCLC患者的安全性和有效性，结果发现 MET扩增患者II期ORR为47%。capmatinib和吉非替尼之间没有明显的药物间相互作用。', '');
INSERT INTO `main_copy` VALUES ('EVI_001066', '一项研究表明，PARP 抑制剂talazoparib和奥拉帕尼与化疗药吉西他滨对NSCLC具有协同活性该组合在NSCLC的H23异种移植模型中表现出显著的体内抗肿瘤活性。', '');
INSERT INTO `main_copy` VALUES ('EVI_001067', '一项研究表明，PARP 抑制剂talazoparib和奥拉帕尼与化疗药吉西他滨对NSCLC具有协同活性该组合在NSCLC的H23异种移植模型中表现出显著的体内抗肿瘤活性。', '');
INSERT INTO `main_copy` VALUES ('EVI_001070', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001071', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001072', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001082', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001083', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001084', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001085', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001087', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001096', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001097', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001098', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001102', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001103', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001104', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001108', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001109', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001111', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001114', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001118', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001119', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001120', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001121', '是FDA批准适用于EGFR 19号外显子缺失或21号外显子 L858R突变的转移性非小细胞肺癌的一线治疗方案。', '');
INSERT INTO `main_copy` VALUES ('EVI_001122', '一项临床研究结果显示一位对索拉非尼敏感的GIST患者为BRAF野生型，而另一位索拉非尼耐药的GIST患者携带BRAF V600E突变', '');
INSERT INTO `main_copy` VALUES ('EVI_001124', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001126', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001130', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001135', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001136', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001137', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001140', '有研究显示epertinib在ERBB2阳性乳腺癌和上消化道癌（包括胃食管交界癌）身上表现出良好的抗肿瘤活性及耐药性。', '');
INSERT INTO `main_copy` VALUES ('EVI_001143', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001144', 'talazoparib对BRCA1和BRCA2（BRCA1/2）种系突变的晚期乳腺癌患者具有抗肿瘤活性。', '');
INSERT INTO `main_copy` VALUES ('EVI_001145', ' talazoparib对BRCA1和BRCA2（BRCA1/2）种系突变的晚期乳腺癌患者具有抗肿瘤活性。', '');
INSERT INTO `main_copy` VALUES ('EVI_001148', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001159', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001171', '研究人员利用实验建立的EGFR-TKI抗性NSCLC细胞系研究了曲美替尼与taselisib联合治疗的疗效，结果表明，使用MEK和PI3K抑制剂的联合治疗是NSCLC的有效治疗策略，可针对EGFR-TKI的获得性抗性。', '');
INSERT INTO `main_copy` VALUES ('EVI_001175', '一项试验纳入90例MET+的晚期肝细胞肝癌患者， 研究发现tepotinib对比索拉非尼可延长TTP及PFS，并且安全性可以接受。', '');
INSERT INTO `main_copy` VALUES ('EVI_001176', 'FDA基于一项包含760例经治疗后的转移性结直肠癌患者的研究结果，批准瑞戈非尼用于KRAS野生型的转移性结直肠癌患者的治疗。', '');
INSERT INTO `main_copy` VALUES ('EVI_001178', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001179', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001183', '一项研究奥拉帕利单药治疗难治性BRCA1/2突变型肝内胆管细胞癌（ICC）患者的试验发现，奥拉帕利治疗BRCA突变相关的难治性晚期ICC是有效的，并且可以耐受不良反应。', '');
INSERT INTO `main_copy` VALUES ('EVI_001184', '一项研究奥拉帕利单药治疗难治性BRCA1/2突变型肝内胆管细胞癌（ICC）患者的试验发现，奥拉帕利治疗BRCA突变相关的难治性晚期ICC是有效的，并且可以耐受不良反应。', '');
INSERT INTO `main_copy` VALUES ('EVI_001185', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001188', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001191', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001192', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001194', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001214', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001218', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001219', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001221', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001222', '一项囊括了29例患者的II期试验评估了Hsp90抑制剂luminespib（AUY922）在EGFR外显子20插入突变的NSCLC患者中的活性。结果提示：Luminespib可能是EGFR 外显子20插入突变的晚期NSCLC患者的积极治疗方法，且具有良好的耐受性。', '');
INSERT INTO `main_copy` VALUES ('EVI_001223', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001227', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001228', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001229', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001231', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001232', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001233', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001235', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001236', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001237', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001239', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001241', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001245', '一项多中心II期试验评估了lurbinectedin对晚期乳腺癌患者的临床活性和耐药的潜在机制显示，lurbinectedin在BRCA1/2突变患者中显示出显著的活性。', '');
INSERT INTO `main_copy` VALUES ('EVI_001246', '一项多中心II期试验评估了lurbinectedin对晚期乳腺癌患者的临床活性和耐药的潜在机制显示，lurbinectedin在BRCA1/2突变患者中显示出显著的活性。', '');
INSERT INTO `main_copy` VALUES ('EVI_001247', '一项II期临床试验，入组HER2扩增的胃食管癌患者，20名接受阿法替尼单药治疗的患者中，5人肿瘤缩小；12名接受阿法替尼联合赫赛汀治疗的患者中，1名患者肿瘤明显缩小，2人肿瘤稳定超过4个月。', '');
INSERT INTO `main_copy` VALUES ('EVI_001248', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001251', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001252', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001253', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001254', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001255', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001256', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001257', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001258', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001259', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001260', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001266', '1个乳腺癌个例报道， 1名63岁的左侧乳腺癌女性患者，肿瘤转移后检测到EGFR外显子19 （p.L747-T751del）缺失突变，使用厄洛替尼治疗，2周后症状明显缓解，肿瘤标志物迅速下降，患者继续使用厄洛替尼作为维持治疗，三个月后，患者完全恢复正常生活，患者的PFS时间已超过9个月。', '');
INSERT INTO `main_copy` VALUES ('EVI_001270', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001272', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001273', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001274', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001275', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001276', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001277', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001278', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001279', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001282', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001283', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001291', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001296', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001297', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001298', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001299', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001300', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001301', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001303', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001306', '一名29岁低分化的胆管癌伴多发性肝内转移和慢性胆管炎的男性患者，NGS检测显示ERBB2基因S310F突变，使用曲妥珠单抗与吉西他滨结合治疗，三个月后，随访成像显示原发肿瘤消退以及转移性病变改善。', '');
INSERT INTO `main_copy` VALUES ('EVI_001307', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001308', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001310', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001311', '一项开放标签的单臂II期临床试验显示，EGFR拷贝数增加的NSCLC患者不应用于厄洛替尼治疗，且由于道德问题，此试验过早停止。针对此类患者此药物可能疗效减弱。', '');
INSERT INTO `main_copy` VALUES ('EVI_001312', '在比较吉非替尼与卡铂+紫杉醇的IPASS研究中，与化疗相比，没有EGFR突变但存在EGFR拷贝数增加的NSCLC患者，吉非替尼的PFS显著缩短。针对此类患者此药物可能疗效减弱。', '');
INSERT INTO `main_copy` VALUES ('EVI_001321', '一例KRAS/NRAS/BRAF野生型，ERBB2扩增的转移性结直肠癌患者，服用阿法替尼后实现3个月无进展生存期。', '');
INSERT INTO `main_copy` VALUES ('EVI_001322', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001323', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001324', 'FDA批准奥拉帕利用于治疗一线铂类化疗后的BRCA突变晚期卵巢、输卵管或原发性腹膜癌。', '');
INSERT INTO `main_copy` VALUES ('EVI_001325', ' FDA批准奥拉帕利用于治疗一线铂类化疗后的BRCA突变晚期卵巢、输卵管或原发性腹膜癌。', '');
INSERT INTO `main_copy` VALUES ('EVI_001326', '一项评估了 142例转移性去势抵抗性前列腺癌患者的双盲、随机、多中心的II期临床试验发现， 奥拉帕利+阿比特龙联合用药显示出良好的PFS及OS。', '');
INSERT INTO `main_copy` VALUES ('EVI_001327', '一项评估了 142例转移性去势抵抗性前列腺癌患者的双盲、随机、多中心的II期临床试验发现， 奥拉帕利+阿比特龙联合用药显示出良好的PFS及OS。', '');
INSERT INTO `main_copy` VALUES ('EVI_001328', '一项113例含MET Exon14-skipping的肺癌患者的临床和基因组数据显示， KRAS突变是MET TKIs（克唑替尼）的可能耐药机制之一。', '');
INSERT INTO `main_copy` VALUES ('EVI_001330', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001332', '一项体外研究生成了三个小鼠模型：ERBB2野生型，ERBB2与EGFR同时突变型，ERBB2突变型。 结果显示，第三代酪氨酸激酶抑制剂奥希替尼并非对所有HER2突变都有效。 奥希替尼与BET抑制剂JQ1的组合对HER2突变型有效。', '');
INSERT INTO `main_copy` VALUES ('EVI_001333', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001334', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001335', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001336', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001337', '一项临床研究表明，HER2扩增可能是肺癌患者对厄洛替尼或阿法替尼联合西妥昔单抗产生耐药的分子机制。', '');
INSERT INTO `main_copy` VALUES ('EVI_001338', '一项临床研究表明，HER2扩增可能是肺癌患者对厄洛替尼或阿法替尼联合西妥昔单抗产生耐药的分子机制。', '');
INSERT INTO `main_copy` VALUES ('EVI_001339', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001340', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001341', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001342', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001343', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001344', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001345', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001346', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001347', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001348', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001349', '一项入组42例晚期胰腺癌患者的单臂II期研究显示，携带致病性的种系或体细胞BRCA1、BRCA2或PALB2突变的胰腺癌患者进行rucaparib治疗，患者表现出良好的PFS、OS，对rucaparib治疗耐受性良好。', '');
INSERT INTO `main_copy` VALUES ('EVI_001350', '一项入组42例晚期胰腺癌患者的单臂II期研究显示，携带致病性的种系或体细胞BRCA1、BRCA2或PALB2突变的胰腺癌患者进行rucaparib治疗，患者表现出良好的PFS、OS，对rucaparib治疗耐受性良好。', '');
INSERT INTO `main_copy` VALUES ('EVI_001351', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001353', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001354', 'NCCN推荐携带BRAF突变的晚期结直肠癌可以采用以上6种联合治疗方案。', '');
INSERT INTO `main_copy` VALUES ('EVI_001355', 'NCCN推荐携带BRAF突变的晚期结直肠癌可以采用以上6种联合治疗方案。', '');
INSERT INTO `main_copy` VALUES ('EVI_001356', 'NCCN推荐携带BRAF突变的晚期结直肠癌可以采用以上6种联合治疗方案。', '');
INSERT INTO `main_copy` VALUES ('EVI_001357', 'NCCN推荐携带BRAF突变的晚期结直肠癌可以采用以上6种联合治疗方案。', '');
INSERT INTO `main_copy` VALUES ('EVI_001359', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001360', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001361', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001362', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001364', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001367', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001368', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001369', '一项体外肿瘤细胞显示针对4种EGFR/HER2外显子20插入突变和激活突变，AP32788能够诱导肿瘤减少，且耐受良好。目前此药物已经在NSCLC患者中进行I/II期临床试验。', '');
INSERT INTO `main_copy` VALUES ('EVI_001373', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001375', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001376', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001377', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001378', '一项临床研究入组的接受过西妥昔单抗或帕尼单抗治疗的170名KRAS野生型结直肠癌（mCRC）患者中，HER2基因扩增最高的患者表现出最差的临床反应。', '');
INSERT INTO `main_copy` VALUES ('EVI_001379', '一项临床研究入组的接受过西妥昔单抗或帕尼单抗治疗的170名KRAS野生型结直肠癌（mCRC）患者中，HER2基因扩增最高的患者表现出最差的临床反应。', '');
INSERT INTO `main_copy` VALUES ('EVI_001380', 'FDA批准ivosidenib用于携带IDH1突变的AML患者的一线治疗。', '');
INSERT INTO `main_copy` VALUES ('EVI_001381', '基于一项FRESCO研究，临床入组经历二线或以上标准化疗失败的转移性结直肠癌患者，对于KRAS野生型患者，呋喹替尼mOS较安慰剂组延长5个月。NMPA批准呋喹替尼用于治疗既往接受过氟尿嘧啶类、奥沙利铂和伊立替康为基础的化疗，以及既往接受过或不适合接受抗血管内皮生长因子 （VEGF）治疗、抗表皮生长因子受体（EGFR）治疗 (RAS野生型）的转移性结直肠癌 （转移性结直肠癌）患者。', '');
INSERT INTO `main_copy` VALUES ('EVI_001382', '有一例ERBB2阳性涎腺导管癌患者，服用曲妥珠单抗联合帕妥珠单抗和多西紫杉醇治疗后达到完全缓解（CR）。', '');
INSERT INTO `main_copy` VALUES ('EVI_001383', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001386', '中国埃克替尼治疗非小细胞肺癌专家共识（2016年版）推荐埃克替尼适用于单药适用于治疗既往接受过至少一个化疗方案失败后的局部晚期或转移性非小细胞肺癌（NSCLC），且EGFR突变型患者疗效优于野生型患者。', '');
INSERT INTO `main_copy` VALUES ('EVI_001387', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001388', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001389', '一项临床研究入组216例NSCLC患者，其中19例患者携带KRAS突变。结果表明：大多数TP53或KRAS突变患者在治疗期间享有持久的临床益处，而大多数野生型患者显示没有持久益处。 更重要的是，同时携带TP53和KRAS突变的4名肺腺癌患者表现出优异的PFS，并且所有患者都具有持久的临床益处。', '');
INSERT INTO `main_copy` VALUES ('EVI_001390', '一项研究针对4名携带KRAS突变的晚期肺腺癌患者，二线治疗后口服阿帕替尼治疗，结果显示阿帕替尼可能是二线治疗后KRAS突变的晚期肺腺癌患者的可能选择。', '');
INSERT INTO `main_copy` VALUES ('EVI_001391', '一项研究显示伴KRAS突变的晚期肺腺癌患者，单剂量纳武利尤单抗治疗后复查发现所有病变均明显缩小（接近完全缓解），2个非靶病变（左胸膜结节和食管旁淋巴结）完全消失。', '');
INSERT INTO `main_copy` VALUES ('EVI_001392', '一项体内体外试验表明MEK抑制剂曲美替尼与CDK4/6抑制剂哌柏西利合用可显著降低KRAS突变型肺癌细胞活性。', '');
INSERT INTO `main_copy` VALUES ('EVI_001393', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001394', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001396', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001397', ' NCCN推荐将奥拉帕利作为维持治疗方案，用于在一线铂类化疗16周内无疾病进展、携带有害生殖细胞BRCA1/2基因突变、PS评分良好的转移性胰腺癌。', '');
INSERT INTO `main_copy` VALUES ('EVI_001398', 'NCCN推荐将奥拉帕利作为维持治疗方案，用于在一线铂类化疗16周内无疾病进展、携带有害生殖细胞BRCA1/2基因突变、PS评分良好的转移性胰腺癌。', '');
INSERT INTO `main_copy` VALUES ('EVI_001399', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001400', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001402', '一项临床研究评估Antroquinonol对两种抗癌治疗失败后的IV期NSCLC患者的疗效。30例入组患者（15名KRAS阳性，15名KRAS阴性），结果显示Antroquinonol单药治疗可提高疾病控制率，延长无进展生存期和总生存期。虽然KRAS野生型和突变型疗效有差，但Antroquinonol仍然适用于KRAS阳性患者。', '');
INSERT INTO `main_copy` VALUES ('EVI_001403', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001405', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001406', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001407', 'Checkmate 057临床试验亚组分析表明，部分携带EGFR激活突变的患者在PFS和OS上并没有获益。包括了多项临床研究的汇总分析也证实了不能延长EGFR突变患者的OS。', '');
INSERT INTO `main_copy` VALUES ('EVI_001410', '在荷兰的四个机构中发现，17名携带EGFR外显子20插入的晚期NSCLC患者接受osimertinib治疗，1例部分缓解，两名患者在截止日期仍在接受osimertinib治疗，中位PFS为3.7个月（95%CI：2.3 - 5.4个月）。一小部分患者（35%）似乎可以从osimertinib治疗中获益超过五个月。', '');
INSERT INTO `main_copy` VALUES ('EVI_001412', '一项II期临床试验的初步数据显示Poziotinib在携带EGFR外显子20插入突变的NSCLC患者亚组中显示出有潜在的活性，这种药物对携带该类EGFR突变的患者总体有效率达73%。', '');
INSERT INTO `main_copy` VALUES ('EVI_001413', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001414', '一项评估奥拉帕利对转移性去势抵抗前列腺癌（mCRPC）患者疗效的II期临床试验显示，存在BRCA1/2突变的患者对奥拉帕利的综合反应率达到83.3%。', '');
INSERT INTO `main_copy` VALUES ('EVI_001415', '一项评估奥拉帕利对转移性去势抵抗前列腺癌（mCRPC）患者疗效的II期临床试验显示，存在BRCA1/2突变的患者对奥拉帕利的综合反应率达到83.3%。', '');
INSERT INTO `main_copy` VALUES ('EVI_001416', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001417', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001418', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001419', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001420', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001421', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001422', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001423', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001424', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001425', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001426', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001427', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001428', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001429', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001430', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001431', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001432', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001433', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001434', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001435', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001436', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001437', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001438', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001439', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001440', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001441', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001442', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001443', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001444', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001445', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001446', '一项I期临床研究（NCT02609776）纳入了108例经治EGFR突变晚期NSCLC患者（其中EGFR三代药耐药，58例； EGFR EXON 20插入突变，27例），27例EGFR EXON 20插入突变患者的总有效率为30%，8例肿瘤部分缓解患者里包括了1例波齐替尼耐药患者。', '');
INSERT INTO `main_copy` VALUES ('EVI_001448', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001449', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001450', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001451', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001452', 'JNJ-372的一项I期临床研究（NCT02609776）纳入了108例经治EGFR突变晚期NSCLC患者， 58例EGFR三代药耐药患者的总有效率为28%，16例肿瘤部分缓解患者里包括了8例C797S突变，3例MET扩增，5例其它耐药机制（非EGFR耐药突变或MET扩增）。', '');
INSERT INTO `main_copy` VALUES ('EVI_001454', 'tepotinib是一种有效的选择性MET抑制剂。一项评估tepotinib + gefitinib与化疗（培美曲塞+顺铂/卡铂）在MET+、EGFR+、T790M-、NSCLC患者疗效的临床试验（NCT01982955），55名患者被随机分配到tepotinib + gefitinib，MET基因扩增的患者中位无进展生存期达到21.2个月。', '');
INSERT INTO `main_copy` VALUES ('EVI_001455', 'NCCN指南中推荐KRAS，NRAS，BRAF野生型的转移性肠癌患者可以使用FOLFOXIRI + 西妥昔单抗联合治疗。', '');
INSERT INTO `main_copy` VALUES ('EVI_001456', 'NCCN指南中推荐KRAS，NRAS，BRAF野生型的转移性肠癌患者可以使用FOLFOXIRI +帕尼单抗联合治疗。', '');
INSERT INTO `main_copy` VALUES ('EVI_001457', 'NCCN指南中推荐KRAS，NRAS，BRAF野生型的转移性肠癌患者可以使用伊立替康 + 帕尼单抗联合治疗。', '');
INSERT INTO `main_copy` VALUES ('EVI_001458', 'NCCN指南中推荐KRAS，NRAS，BRAF野生型的转移性肠癌患者可以使用伊立替康 + 西妥昔单抗联合治疗。', '');
INSERT INTO `main_copy` VALUES ('EVI_001459', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001460', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001461', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001462', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001463', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001464', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001465', 'FDA批准rucaparib用于对铂类化疗有完全或部分反应的复发性上皮性卵巢癌、输卵管癌或原发性腹膜癌患者的维持治疗。', '');
INSERT INTO `main_copy` VALUES ('EVI_001466', 'FDA批准rucaparib用于对铂类化疗有完全或部分反应的复发性上皮性卵巢癌、输卵管癌或原发性腹膜癌患者的维持治疗。', '');
INSERT INTO `main_copy` VALUES ('EVI_001467', 'FDA批准rucaparib用于对铂类化疗有完全或部分反应的复发性上皮性卵巢癌、输卵管癌或原发性腹膜癌患者的维持治疗。', '');
INSERT INTO `main_copy` VALUES ('EVI_001468', 'FDA批准rucaparib用于对铂类化疗有完全或部分反应的复发性上皮性卵巢癌、输卵管癌或原发性腹膜癌患者的维持治疗。', '');
INSERT INTO `main_copy` VALUES ('EVI_001469', '（NCT01286987）临床试验研究显示，Talazoparib对于携带BRCA1/2有害突变的卵巢癌、胰腺癌的患者有较好的抗肿瘤活性。', '');
INSERT INTO `main_copy` VALUES ('EVI_001470', '（NCT01286987）临床试验研究显示，Talazoparib对于携带BRCA1/2有害突变的卵巢癌、胰腺癌的患者有较好的抗肿瘤活性。', '');
INSERT INTO `main_copy` VALUES ('EVI_001471', '（NCT01286987）临床试验研究显示，Talazoparib对于携带BRCA1/2有害突变的卵巢癌、胰腺癌的患者有较好的抗肿瘤活性。', '');
INSERT INTO `main_copy` VALUES ('EVI_001472', '（NCT01286987）临床试验研究显示，Talazoparib对于携带BRCA1/2有害突变的卵巢癌、胰腺癌的患者有较好的抗肿瘤活性。', '');
INSERT INTO `main_copy` VALUES ('EVI_001473', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001476', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001477', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001478', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001479', 'RO5126766是一种有效的RAF和MEK抑制剂，在RAS和RAF突变的癌症的异种移植模型中具有抗肿瘤活性。', '');
INSERT INTO `main_copy` VALUES ('EVI_001480', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001481', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001482', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001483', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001484', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001485', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001486', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001487', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001488', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001489', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001490', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001491', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001492', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001493', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001494', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001495', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001496', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001497', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001498', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001499', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001500', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001501', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001502', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001503', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001504', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001505', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001506', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001509', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001510', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001511', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001512', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001514', '一项吡咯替尼II期临床试验，入组15名HER2 20外显子突变的NSCLC患者进行初步安全性和有效性研究，结果显示400 mg吡格替尼的客观缓解率为53.3%，中位无进展生存期为6.4个月，研究表明吡咯替尼可能对携带HER2 20外显子突变的NSCLC有一定的抗肿瘤作用。', '');
INSERT INTO `main_copy` VALUES ('EVI_001515', 'MSKCC癌症中心发表在clinical cancer research上的研究结果显示，PI3K-MTOR途径中存在活化突变的患者，其索拉非尼治疗的临床获益率较非PI3K-MTOR肿瘤患者较低。', '');
INSERT INTO `main_copy` VALUES ('EVI_001516', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001517', '一项研究招募了40个FGFR mRNA表达异常的NSCLC患者用rogaratinib进行治疗，结果显示，患者对Rogaratinib耐受性良好， 36个接受治疗的患者具有可评估的反应。总体反应率为5.6%，疾病控制率为64%。在所有FGFR亚型中mRNA过表达患者皆实现了疾病稳定。', '');
INSERT INTO `main_copy` VALUES ('EVI_001518', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001519', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001520', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001521', '一项infigratinib的临床试验中，36例使用连续剂量 ≥100mg治疗的FGFR1扩增sqNSCLC（鳞状非小细胞肺癌）患者的疾病控制率为50%；4名患者（11.1%）达到PR（部分缓解），14名患者SD。', '');
INSERT INTO `main_copy` VALUES ('EVI_001522', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001523', '通过细胞系和小鼠模型的研究发现，MLL2和PIK3CA突变似乎对使用infigratinib治疗的携带FGFR1扩增的患者具有负面影响。', '');
INSERT INTO `main_copy` VALUES ('EVI_001524', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001525', '一项多中心，开放标签的II期临床试验（NCT02150967）评估了infigratinib对≥18岁、晚期或转移性胆管癌患者（患者携带FGFR2融合或其他FGFR改变）的疗效，患者总反应率为14.8%（FGFR2融合类患者为18.8%），疾病控制率为75.4%（FGFR2融合类患者为83.3%），估计中位无进展生存期为5.8个月。', '');
INSERT INTO `main_copy` VALUES ('EVI_001526', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001529', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001530', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001531', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001532', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001533', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001534', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001535', '重新分析来自OPUS研究的患者样本，RAS突变型转移性结直肠癌患者，FOLFOX4联合西妥昔单抗不能使患者受益，可能还会产生有害影响。', '');
INSERT INTO `main_copy` VALUES ('EVI_001536', '重新分析来自OPUS研究的患者样本，RAS突变型转移性结直肠癌患者，FOLFOX4联合西妥昔单抗不能使患者受益，可能还会产生有害影响。', '');
INSERT INTO `main_copy` VALUES ('EVI_001537', '一项III期临床试验显示携带RAS突变的患者，帕尼单抗-FOLFOX4联合治疗后患者的无进展生存期和总生存率低于野生型患者。一项对1183例转移性结直肠癌患者的随机临床III期试验结果表明，在携带KRAS突变的患者中，帕尼单抗联合FOLFOX组患者具有缩短的总生存期以及无进展生存期。', '');
INSERT INTO `main_copy` VALUES ('EVI_001538', '一项III期临床试验显示携带RAS突变的患者，帕尼单抗-FOLFOX4联合治疗后患者的无进展生存期和总生存率低于野生型患者。', '');
INSERT INTO `main_copy` VALUES ('EVI_001542', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001543', '研究发现，FGFR1基因扩增在非小细胞肺鳞癌中的发生率为12.5%，在非小细胞肺腺癌中的发生率为7%。细胞实验中，在五种FGFR1扩增的鳞状NSCLC PDTX模型（肿瘤异种移植模型）中，AZD-4547可以诱导其中4个模型的肿瘤停滞或退化。', '');
INSERT INTO `main_copy` VALUES ('EVI_001544', '一项研究发现携带FGFR1扩增的非小细胞肺癌细胞系的增殖依赖于FGFR1蛋白酶活性，用FGFR1特异性shRNA或FGFR小分子酶抑制剂（PD173074或FIIN-1）处理该细胞系会导致肿瘤细胞生长抑制。', '');
INSERT INTO `main_copy` VALUES ('EVI_001545', '一项研究发现携带FGFR1扩增的非小细胞肺癌细胞系的增殖依赖于FGFR1蛋白酶活性，用FGFR1特异性shRNA或FGFR小分子酶抑制剂（PD173074或FIIN-1）处理该细胞系会导致肿瘤细胞生长抑制。', '');
INSERT INTO `main_copy` VALUES ('EVI_001546', '一项研究中评估了nintedanib在FGFR1拷贝数增加阳性的LSCC细胞系中的抗肿瘤活性，纳入了75个FGFR改变临床LSCC标本，结果显示Nintedanib在体外和体内可以抑制FGFR1 CNG阳性LSCC细胞系的增殖。', '');
INSERT INTO `main_copy` VALUES ('EVI_001547', '在一项对1186例转移结直肠癌患者的随机III期临床试验结果表明，携带KRAS突变的患者可能不会从帕尼单抗联合FOLFIRI治疗中获益。', '');
INSERT INTO `main_copy` VALUES ('EVI_001548', '在一项对1186例转移结直肠癌患者的随机III期临床试验结果表明，携带RAS突变的患者可能不会从帕尼单抗联合FOLFIRI治疗中获益。', '');
INSERT INTO `main_copy` VALUES ('EVI_001549', '一项入组了592例晚期结直肠癌患者的开放标签随机III期临床试验发现，对于携带任何KRAS、NRAS突变的患者，接受西妥昔单抗联合FOLFIRI疗法的无进展生存期显著短于贝伐单抗联合疗法。', '');
INSERT INTO `main_copy` VALUES ('EVI_001550', '一项入组了592例晚期结直肠癌患者的开放标签随机III期临床试验发现，对于携带任何KRAS、NRAS突变的患者，接受西妥昔单抗联合FOLFIRI疗法的无进展生存期显著短于贝伐单抗联合疗法。', '');
INSERT INTO `main_copy` VALUES ('EVI_001551', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001552', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001553', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001555', '一项汇总分析包括了三项临床研究（checkmate 057, keynote 010, and POPLAR），证实了免疫检查点抑制剂不能增强EGFR突变患者的OS；包括了多项临床研究的汇总分析也证实了免疫检查点抑制剂不能延长EGFR突变患者的OS。', '');
INSERT INTO `main_copy` VALUES ('EVI_001556', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001557', '一项pembrolizumab的II期试验(NCT02879994)显示，在10例PD-L1阳性且EGFR突变（包括Exon 19del, Exon 20ins, p.L858R）的患者缺乏客观反应，包括7例PD-L1表达>50%的患者。此外，多项临床研究总分析（checkmate 057, Checkmate 017，keynote 010, OAK and POPLAR）也证实了免疫检查点抑制剂不能增强EGFR突变患者的OS。', '');
INSERT INTO `main_copy` VALUES ('EVI_001558', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001559', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001560', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001561', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001562', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001563', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001565', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001566', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001567', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001568', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001569', '中国临床肿瘤学会（CSCO）以2A类证据推荐RAS、BRAF基因野生型或突变均可以行化疗联合贝伐珠单抗的治疗方案。', '');
INSERT INTO `main_copy` VALUES ('EVI_001570', '中国临床肿瘤学会（CSCO）以2A类证据推荐RAS、BRAF基因野生型或突变均可以行化疗联合贝伐珠单抗的治疗方案。', '');
INSERT INTO `main_copy` VALUES ('EVI_001571', '中国临床肿瘤学会（CSCO）以2A类证据推荐RAS、BRAF基因野生型或突变均可以行化疗联合贝伐珠单抗的治疗方案。', '');
INSERT INTO `main_copy` VALUES ('EVI_001572', '中国临床肿瘤学会（CSCO）以2A类证据推荐RAS、BRAF基因野生型或突变均可以行化疗联合贝伐珠单抗的治疗方案。', '');
INSERT INTO `main_copy` VALUES ('EVI_001573', '中国临床肿瘤学会（CSCO）以2A类证据推荐RAS、BRAF基因野生型或突变均可以行化疗联合贝伐珠单抗的治疗方案。', '');
INSERT INTO `main_copy` VALUES ('EVI_001574', '中国临床肿瘤学会（CSCO）以2A类证据推荐RAS、BRAF基因野生型或突变均可以行化疗联合贝伐珠单抗的治疗方案。', '');
INSERT INTO `main_copy` VALUES ('EVI_001575', '中国临床肿瘤学会（CSCO）以2A类证据推荐RAS、BRAF基因野生型或突变均可以行化疗联合贝伐珠单抗的治疗方案。', '');
INSERT INTO `main_copy` VALUES ('EVI_001576', '中国临床肿瘤学会（CSCO）以2A类证据推荐RAS、BRAF基因野生型或突变均可以行化疗联合贝伐珠单抗的治疗方案。', '');
INSERT INTO `main_copy` VALUES ('EVI_001577', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001578', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001579', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001580', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001581', '中国临床肿瘤学会（CSCO）以1A类证据推荐已接受过奥沙利铂和伊立替康治疗的RAS或BRAF突变型结直肠癌可行呋喹替尼治疗。', '');
INSERT INTO `main_copy` VALUES ('EVI_001582', '中国临床肿瘤学会（CSCO）以1A类证据推荐已接受过奥沙利铂和伊立替康治疗的RAS或BRAF突变型结直肠癌可行呋喹替尼治疗。', '');
INSERT INTO `main_copy` VALUES ('EVI_001583', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001584', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001585', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001586', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001593', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001594', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001595', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001596', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001598', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001599', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001600', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001601', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001602', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001603', '中国临床肿瘤学会（CSCO）以1A类证据推荐已接受过奥沙利铂和伊立替康治疗的RAS或BRAF突变型结直肠癌可行regorafenib治疗。', '');
INSERT INTO `main_copy` VALUES ('EVI_001604', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001605', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001606', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001607', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001608', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001609', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001610', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001611', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001613', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001614', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001615', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001617', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001618', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001619', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001620', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001622', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001627', 'NEJ009研究结果发表于《临床肿瘤学杂志》，该研究旨在评估吉非替尼+卡铂+培美曲塞对比吉非替尼用于EGFR敏感突变晚期NSCLC的疗效和安全性。结果显示，联合组和吉非替尼组的ORR分别为84%和67%（P＜0.001），PFS分别为20.9个月和11.2个月， MST分别为50.9个月和38.8个月。', '');
INSERT INTO `main_copy` VALUES ('EVI_001628', 'NEJ009研究结果发表于《临床肿瘤学杂志》，该研究旨在评估吉非替尼+卡铂+培美曲塞对比吉非替尼用于EGFR敏感突变晚期NSCLC的疗效和安全性。结果显示，联合组和吉非替尼组的ORR分别为84%和67%（P＜0.001），PFS分别为20.9个月和11.2个月， MST分别为50.9个月和38.8个月。', '');
INSERT INTO `main_copy` VALUES ('EVI_001629', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001630', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001631', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001632', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001633', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001634', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001637', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001638', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001639', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001640', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001642', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001643', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001644', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001645', '非小细胞肺癌NCCN指南推荐EGFR 19号外显子缺失、p.L858R、p.L861Q、p.G719X、p.S768I这些突变与酪氨酸激酶抑制剂的敏感性有显著关联，携带这些突变之一的患者对酪氨酸激酶抑制剂（如厄洛替尼、吉非替尼、阿法替尼、奥希替尼、达可替尼）敏感。', '');
INSERT INTO `main_copy` VALUES ('EVI_001646', '非小细胞肺癌NCCN指南推荐EGFR 19号外显子缺失、p.L858R、p.L861Q、p.G719X、p.S768I这些突变与酪氨酸激酶抑制剂的敏感性有显著关联，携带这些突变之一的患者对酪氨酸激酶抑制剂（如厄洛替尼、吉非替尼、阿法替尼、奥希替尼、达可替尼）敏感。', '');
INSERT INTO `main_copy` VALUES ('EVI_001647', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001648', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001649', '非小细胞肺癌NCCN指南推荐EGFR 19号外显子缺失、p.L858R、p.L861Q、p.G719X、p.S768I这些突变与酪氨酸激酶抑制剂的敏感性有显著关联，携带这些突变之一的患者对酪氨酸激酶抑制剂（如厄洛替尼、吉非替尼、阿法替尼、奥希替尼、达可替尼）敏感。', '');
INSERT INTO `main_copy` VALUES ('EVI_001650', '非小细胞肺癌NCCN指南推荐EGFR 19号外显子缺失、p.L858R、p.L861Q、p.G719X、p.S768I这些突变与酪氨酸激酶抑制剂的敏感性有显著关联，携带这些突变之一的患者对酪氨酸激酶抑制剂（如厄洛替尼、吉非替尼、阿法替尼、奥希替尼、达可替尼）敏感。', '');
INSERT INTO `main_copy` VALUES ('EVI_001651', '非小细胞肺癌NCCN指南推荐EGFR 19号外显子缺失、p.L858R、p.L861Q、p.G719X、p.S768I这些突变与酪氨酸激酶抑制剂的敏感性有显著关联，携带这些突变之一的患者对酪氨酸激酶抑制剂（如厄洛替尼、吉非替尼、阿法替尼、奥希替尼、达可替尼）敏感。', '');
INSERT INTO `main_copy` VALUES ('EVI_001652', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001653', '非小细胞肺癌NCCN指南推荐EGFR 19号外显子缺失、p.L858R、p.L861Q、p.G719X、p.S768I这些突变与酪氨酸激酶抑制剂的敏感性有显著关联，携带这些突变之一的患者对酪氨酸激酶抑制剂（如厄洛替尼、吉非替尼、阿法替尼、奥希替尼、达可替尼）敏感。', '');
INSERT INTO `main_copy` VALUES ('EVI_001654', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001655', '非小细胞肺癌NCCN指南推荐EGFR 19号外显子缺失、p.L858R、p.L861Q、p.G719X、p.S768I这些突变与酪氨酸激酶抑制剂的敏感性有显著关联，携带这些突变之一的患者对酪氨酸激酶抑制剂（如厄洛替尼、吉非替尼、阿法替尼、奥希替尼、达可替尼）敏感。', '');
INSERT INTO `main_copy` VALUES ('EVI_001656', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001657', '非小细胞肺癌NCCN指南推荐EGFR 19号外显子缺失、p.L858R、p.L861Q、p.G719X、p.S768I这些突变与酪氨酸激酶抑制剂的敏感性有显著关联，携带这些突变之一的患者对酪氨酸激酶抑制剂（如厄洛替尼、吉非替尼、阿法替尼、奥希替尼、达可替尼）敏感。', '');
INSERT INTO `main_copy` VALUES ('EVI_001658', '非小细胞肺癌NCCN指南推荐EGFR 19号外显子缺失、p.L858R、p.L861Q、p.G719X、p.S768I这些突变与酪氨酸激酶抑制剂的敏感性有显著关联，携带这些突变之一的患者对酪氨酸激酶抑制剂（如厄洛替尼、吉非替尼、阿法替尼、奥希替尼、达可替尼）敏感。', '');
INSERT INTO `main_copy` VALUES ('EVI_001659', '非小细胞肺癌NCCN指南推荐EGFR 19号外显子缺失、p.L858R、p.L861Q、p.G719X、p.S768I这些突变与酪氨酸激酶抑制剂的敏感性有显著关联，携带这些突变之一的患者对酪氨酸激酶抑制剂（如厄洛替尼、吉非替尼、阿法替尼、奥希替尼、达可替尼）敏感。', '');
INSERT INTO `main_copy` VALUES ('EVI_001660', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001661', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001662', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001663', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001664', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001665', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001666', '在一项Ib期试验（TATTON）的剂量探索研究中，osimertinib和Selumetinib联合治疗对EGFR突变型非小细胞肺癌患者的部分缓解率为42%，稳定疾病率为39%；在剂量扩展组中，部分缓解为34%,稳定疾病率为23%。', '');
INSERT INTO `main_copy` VALUES ('EVI_001667', '在一项Ib期试验（TATTON）的剂量探索研究中，osimertinib和Selumetinib联合治疗对EGFR突变型非小细胞肺癌患者的部分缓解率为42%，稳定疾病率为39%；在剂量扩展组中，部分缓解为34%,稳定疾病率为23%。', '');
INSERT INTO `main_copy` VALUES ('EVI_001669', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001670', '在一项II期临床试验中，Apitolisib（GDC-0980）的耐受性较差，但在具有PIK3CA，PTEN或AKT1突变的子宫内膜癌患者中显示出了疗效。', '');
INSERT INTO `main_copy` VALUES ('EVI_001671', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001672', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001673', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001674', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001675', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001676', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001677', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001678', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001679', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001680', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001681', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001682', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001683', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001684', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001685', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001687', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001688', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001691', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001693', '在BASALT-2、BASALT-3临床试验中，患者接受80或100 mg buparlisib治疗，总体缓解率（完全缓解+ PR）在80 mg时为6%，在100 mg时为18%。所有患者均因疾病进展而终止治疗。基于以上研究，buparlisib目前将不会在肺癌中进一步发展。', '');
INSERT INTO `main_copy` VALUES ('EVI_001695', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001696', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001697', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001698', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001699', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001701', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001702', ' 在一项II期临床试验中，携带ERBB2基因扩增或过表达的非小细胞肺癌患者使用trastuzumab和pertuzumab联合治疗，客观缓解率为13%（2/16），病情稳定超过120天的患者为13%（2/16）。', '');
INSERT INTO `main_copy` VALUES ('EVI_001703', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001704', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001705', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001706', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001707', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001708', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001709', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001710', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001711', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001712', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001713', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001714', '一个随机、前瞻性、多中心的III期临床试验，评估了trastuzumab在HER2阳性晚期胃癌和EGJ腺癌中的疗效和安全性，患者随机分配接受trastuzumab加化疗（cisplatin + fluorouracil 或 capecitabine）或单独接受化疗。HER2阳性患者在化疗中加入trastuzumab后中位OS显着改善（分别为13.8和11个月； P = .046）。 这项研究建立了trastuzumab联合顺铂和氟嘧啶作为HER2阳性转移性胃食管腺癌患者的标准治疗方法。', '');
INSERT INTO `main_copy` VALUES ('EVI_001715', '一个随机、前瞻性、多中心的III期临床试验，评估了trastuzumab在HER2阳性晚期胃癌和EGJ腺癌中的疗效和安全性，患者随机分配接受trastuzumab加化疗（cisplatin + fluorouracil 或 capecitabine）或单独接受化疗。HER2阳性患者在化疗中加入trastuzumab后中位OS显着改善（分别为13.8和11个月； P = .046）。 这项研究建立了trastuzumab联合顺铂和氟嘧啶作为HER2阳性转移性胃食管腺癌患者的标准治疗方法。', '');
INSERT INTO `main_copy` VALUES ('EVI_001716', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001721', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001722', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001723', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001724', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001725', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001726', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001727', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001728', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001729', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001730', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001731', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001733', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001734', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001735', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001737', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001738', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001739', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001740', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001741', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001742', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001743', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001744', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001745', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001747', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001748', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001749', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001750', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001751', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001752', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001753', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001757', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001758', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001759', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001760', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001761', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001762', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001763', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001764', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001765', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001766', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001767', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001768', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001769', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001770', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001771', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001772', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001773', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001774', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001775', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001776', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001777', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001781', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001782', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001783', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001784', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001785', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001786', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001787', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001792', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001793', 'NCCN指南中推荐KRAS，NRAS，BRAF野生型、HER2阳性的转移性肠癌患者可以使用trastuzumab + pertuzumab联合治疗。', '');
INSERT INTO `main_copy` VALUES ('EVI_001794', 'NCCN指南中推荐KRAS，NRAS，BRAF野生型、HER2阳性的转移性肠癌患者可以使用trastuzumab + lapatinib联合治疗。', '');
INSERT INTO `main_copy` VALUES ('EVI_001795', 'NCCN指南推荐III/IV期或复发的HER2表达阳性的子宫浆液性癌患者使用卡铂 + 紫杉醇联合曲妥珠单抗的组合治疗方案。', '');
INSERT INTO `main_copy` VALUES ('EVI_001796', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001797', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001798', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001799', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001800', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001801', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001802', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001803', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001804', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001806', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001807', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001808', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001809', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001810', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001811', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001812', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001813', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001814', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001815', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001816', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001817', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001818', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001819', '', '');
INSERT INTO `main_copy` VALUES ('EVI_001820', '', '');

SET FOREIGN_KEY_CHECKS = 1;
